[EV-688] [.NET] [feat] complete mysql database
LucasPerinWarren/everest-03-dotnet pull request #5
Opened 2022-09-16 21:15 UTC by LucasPerinWarren

**Documentação técnica**
Será necessário criar um novo projeto classlib(Infrastructure.Data) que conterá todas as migrations, mappings e DbContext.

_Utilizar ORM EFCore(Entity Framework Core)._
[Configuração banco de dados com pacote:](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#readme) 

_Pomelo.EntityFrameworkCore.MySql_
Connection na appsettings.json deve conter criação do banco de dados, usuário, senha;

[Mapping](https://docs.microsoft.com/pt-br/ef/core/modeling/#grouping-configuration) da entidade Customer;

_Para executar Migrations será utilizado o pacote Nuget:_

Microsoft.EntityFrameworkCore.Tools

**Critérios para aceitação**
Aplicar Configurations/Mappings [via Assembly](https://docs.microsoft.com/pt-br/ef/core/modeling/#grouping-configuration).

2022-09-19 18:19 UTC, LeonardoAlthoff commented on Customer.API/Customer.API.csproj
>    </ItemGroup>
A API não pode ter acesso à camada de Data
```suggestion
  <ItemGroup>
    <ProjectReference Include="..\Customer.AppServices\Customer.AppServices.csproj" />
  </ItemGroup>
```

2022-09-19 18:24 UTC, LeonardoAlthoff commented on Customer.DomainServices/Customer.DomainServices.csproj
> +    <ProjectReference Include="..\Customer.Infrastructure.Data\Customer.Infrastructure.Data.csproj" />
Como o Infrastructure.Data já contempla o DomainModels, não há necessidade de referenciá-lo aqui.
```suggestion
  <ItemGroup>
    <ProjectReference Include="..\Customer.Infrastructure.Data\Customer.Infrastructure.Data.csproj" />
```

2022-09-19 18:26 UTC, LeonardoAlthoff commented on Customer.DomainServices/Services/CustomerService.cs
Prefira retornar a interface que abrange o tipo List. Trocar retorno para IEnumerable ou IList

2022-09-19 18:28 UTC, LeonardoAlthoff commented on Customer.DomainServices/Services/CustomerService.cs
> +            var context = _featureContext.Set<CustomersModel>();
Igual comentário anterior

2022-09-19 18:28 UTC, LeonardoAlthoff commented on Customer.DomainServices/Services/CustomerService.cs
>              {
```suggestion

            varcustomerToDelete = context.FirstOrDefault(x => x.Id == id);
            if (customerToDelete is null)
            {
```

2022-09-19 18:29 UTC, LeonardoAlthoff commented on Customer.DomainServices/Services/CustomerService.cs
> +            var context = _featureContext.Set<CustomersModel>();
Igual comentário anterior

2022-09-19 18:32 UTC, LeonardoAlthoff commented on Customer.Infrastructure.Data/Migrations/20220916205007_MyFirstMigration.cs
> +                    FullName = table.Column<string>(type: "varchar(100)", nullable: false)
Alterar para varchar(250), pois existem nomes com mais de 100 caracteres

2022-09-19 18:35 UTC, LeonardoAlthoff commented on Customer.Infrastructure.Data/Migrations/20220916205007_MyFirstMigration.cs
> +                        .Annotation("MySql:CharSet", "utf8mb4"),
Não há razão para existir uma coluna com o e-mail de confirmação. O propósito dele termina na camada de aplicação, o que será salvo no banco de dados será somente o campo e-mail normal. Será necessário alterar também no "CustomersModel". Aliás, por se tratar do modelo de apenas um cliente, alterar o nome para o singular também.

2022-09-19 18:37 UTC, LeonardoAlthoff commented on Customer.Infrastructure.Data/Migrations/20220916205007_MyFirstMigration.cs
> +                        .Annotation("MySql:CharSet", "utf8mb4"),
Você deixou apenas 12 caracteres para o telefone. No construtor do CustomerModel, há formatação para retirar eventuais caracteres especiais, como "+", "()", "-"? Ademais, é possível que o telefone seja internacional e, além do DDD, seja necessário acrescentar o código do pais. Por esse motivo, acredito que o tamanho desse campo deva ser aumentado.

2022-09-19 18:41 UTC, LeonardoAlthoff commented on Customer.Infrastructure.Data/Migrations/20220916205007_MyFirstMigration.cs
> +    }
Após realizar as alterações, transforme todas as migrations em apenas uma só

2022-09-19 18:43 UTC, LeonardoAlthoff commented on Customer.DomainModels/Properties/launchSettings.json
> +{
Qual a utilidade desse arquivo?

2022-09-19 18:43 UTC, LeonardoAlthoff commented on Customer.DomainServices/Properties/launchSettings.json
> +{
Qual a utilidade desse arquivo?

2022-09-19 18:43 UTC, LeonardoAlthoff commented on Customer.AppServices/Properties/launchSettings.json
> +{
Qual a utilidade desse arquivo?

2022-09-19 18:43 UTC, LeonardoAlthoff requested changes
Verificar comentários

2022-09-20 15:54 UTC, LeonardoAlthoff commented on Customer.DomainServices/Services/CustomerService.cs
> +            }
Aqui você está jogando as exceptions ao contrário. Quando não encontra com o ID, deve retornar ArgumentNullExceptions, e quando encontra com CPF ou E-mail igual, deve retornar ArgumentException

2022-09-20 16:04 UTC, LeonardoAlthoff requested changes
Revisar comentário

2022-09-20 17:40 UTC, viniciusoliveira-warren commented on Customer.API/Customer.API.csproj
> +    <UserSecretsId>3bb12436-245f-4fb6-b27e-be5f1def4ed7</UserSecretsId>
Onde essa key está sendo usada?

2022-09-20 17:41 UTC, viniciusoliveira-warren commented on Customer.AppServices/Profile/CustomerProfile.cs
> +            CreateMap<CustomerModel, GetCustomerDto>();
Renomear GetCustomerDto para CustomerResult

2022-09-20 17:42 UTC, viniciusoliveira-warren commented on Customer.AppServices/Services/CustomerAppService.cs
> +        public IList<GetCustomerDto> Get()
Retornar de preferencia IEnumerable porque:

Se quem está chamando esse método pode manipular (adicionar/remover) os itens da coleção, então o retorno pode ser um IList.

Se quem está chamando deve apenas iterar em cima ou usar funcionalidades básicas, então na perspectiva de design sempre é preferível usar o tipo menos derivado possível (IEnumerable ou ICollection).

2022-09-20 17:45 UTC, viniciusoliveira-warren commented on Customer.DomainModels/Models/CustomerModel.cs
> +    public class CustomerModel : BaseModel
Já estamos na camada de DomainModel então é redundante ter o sufixo Model

2022-09-20 17:46 UTC, viniciusoliveira-warren commented on Customer.DomainServices/Services/CustomerService.cs
> +            return _customers.ToList();
Esse ToList está aqui apenas para consumir mais memória e degradar performance
```suggestion
            return _customers;
```

2022-09-20 17:46 UTC, viniciusoliveira-warren commented on Customer.DomainServices/Services/CustomerService.cs
> +            if (_customers.Any(x => x.Email == customer.Email || x.Cpf == customer.Cpf))
```suggestion
        {
            if (_customers.Any(x => x.Email == customer.Email || x.Cpf == customer.Cpf))
```

2022-09-20 17:47 UTC, viniciusoliveira-warren commented on Customer.Infrastructure.Data/Mapping/CustomerMapping.cs
> +                .HasColumnName("id");
```suggestion
                .HasColumnName("Id");
```

2022-09-20 17:51 UTC, viniciusoliveira-warren commented on Customer.AppServices/Services/CustomerAppService.cs
> +            return _mapper.Map<List<CustomerResult>>(customerList);
Retornar IEnumerable porque:

Se quem está chamando esse método pode manipular (adicionar/remover) os itens da coleção, então o retorno pode ser um IList.

Se quem está chamando deve apenas iterar em cima ou usar funcionalidades básicas, então na perspectiva de design sempre é preferível usar o tipo menos derivado possível (IEnumerable ou ICollection).

2022-09-20 17:51 UTC, viniciusoliveira-warren commented on Customer.AppServices/Services/CustomerAppService.cs
> +            CustomerModel customer = _mapper.Map<CustomerModel>(updateCustomer);
```suggestion
            var customer = _mapper.Map<CustomerModel>(updateCustomer);
```

2022-09-20 20:10 UTC, viniciusoliveira-warren commented on AppServices/AppServices.csproj
> +  </ItemGroup>
```suggestion
  <ItemGroup>
    <ProjectReference Include="..\AppModels\AppModels.csproj" />
    <ProjectReference Include="..\DomainServices\DomainServices.csproj" />
  </ItemGroup>
```

2022-09-20 20:13 UTC, viniciusoliveira-warren commented on WarrenEverest.API/WarrenEverest.API.csproj
>    </ItemGroup>
```suggestion
    <ProjectReference Include="..\AppServices\AppServices.csproj" />
  </ItemGroup>
```

2022-09-20 20:16 UTC, viniciusoliveira-warren approved these changes

2022-09-20 20:19 UTC, merged